language: go
sudo: false

addons:
  apt:
    packages:
      - gfortran

install:
  - go get -d -t ./...
  - (cd $HOME/gopath/src/github.com/simulated-reality/hotspot && make install)
  - (cd $HOME/gopath/src/github.com/ready-steady/lapack && make install)

notifications:
  email: false
