language: go

before_install:
  - sudo apt-get install gfortran

install:
  - go get -d -t ./...

  - cd $HOME/gopath/src/github.com/ready-steady/hotspot
  - git submodule init
  - git submodule update
  - make install
  - cd -

  - cd $HOME/gopath/src/github.com/ready-steady/linear/lapack
  - git submodule init
  - git submodule update
  - make install
  - cd -

notifications:
  email:
    on_success: never
