language: go

before_install:
  - sudo apt-get install gfortran

install:
  - go get -d -t ./...
  - (cd $HOME/gopath/src/github.com/ready-steady/linear/lapack && make install)

notifications:
  email:
    on_success: never
